// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum PasteLabelStyle: Int {
  case automatic = 0
  case titleOnly = 1
  case iconOnly = 2
  case titleAndIcon = 3
}

enum PasteAlignmentDirection: Int {
  case horizontal = 0
  case vertical = 1
}

enum PasteAlignment: Int {
  case bottom = 0
  case bottomLeading = 1
  case bottomTrailing = 2
  case center = 3
  case centerFirstTextBaseline = 4
  case centerLastTextBaseline = 5
  case leading = 6
  case leadingFirstTextBaseline = 7
  case leadingLastTextBaseline = 8
  case top = 9
  case topLeading = 10
  case topTrailing = 11
  case trailing = 12
  case trailingFirstTextBaseline = 13
  case trailingLastTextBaseline = 14
}

enum PasteButtonBorderShape: Int {
  case automatic = 0
  case roundedRectangle = 1
  case capsule = 2
  case circle = 3
}

enum VersionOverride: Int {
  case iOS14 = 0
  case iOS13 = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PasteColor: Hashable {
  var r: Double
  var g: Double
  var b: Double
  var a: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PasteColor? {
    let r = pigeonVar_list[0] as! Double
    let g = pigeonVar_list[1] as! Double
    let b = pigeonVar_list[2] as! Double
    let a = pigeonVar_list[3] as! Double

    return PasteColor(
      r: r,
      g: g,
      b: b,
      a: a
    )
  }
  func toList() -> [Any?] {
    return [
      r,
      g,
      b,
      a,
    ]
  }
  static func == (lhs: PasteColor, rhs: PasteColor) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PasteButtonParams: Hashable {
  var color: PasteColor? = nil
  var labelStyle: PasteLabelStyle? = nil
  var buttonBorderShape: PasteButtonBorderShape? = nil
  var buttonBorderShapeRadius: Double? = nil
  var width: Double? = nil
  var height: Double? = nil
  var alignment: PasteAlignment? = nil
  var versionOverride: VersionOverride? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PasteButtonParams? {
    let color: PasteColor? = nilOrValue(pigeonVar_list[0])
    let labelStyle: PasteLabelStyle? = nilOrValue(pigeonVar_list[1])
    let buttonBorderShape: PasteButtonBorderShape? = nilOrValue(pigeonVar_list[2])
    let buttonBorderShapeRadius: Double? = nilOrValue(pigeonVar_list[3])
    let width: Double? = nilOrValue(pigeonVar_list[4])
    let height: Double? = nilOrValue(pigeonVar_list[5])
    let alignment: PasteAlignment? = nilOrValue(pigeonVar_list[6])
    let versionOverride: VersionOverride? = nilOrValue(pigeonVar_list[7])

    return PasteButtonParams(
      color: color,
      labelStyle: labelStyle,
      buttonBorderShape: buttonBorderShape,
      buttonBorderShapeRadius: buttonBorderShapeRadius,
      width: width,
      height: height,
      alignment: alignment,
      versionOverride: versionOverride
    )
  }
  func toList() -> [Any?] {
    return [
      color,
      labelStyle,
      buttonBorderShape,
      buttonBorderShapeRadius,
      width,
      height,
      alignment,
      versionOverride,
    ]
  }
  static func == (lhs: PasteButtonParams, rhs: PasteButtonParams) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PasteLabelStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PasteAlignmentDirection(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PasteAlignment(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PasteButtonBorderShape(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VersionOverride(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return PasteColor.fromList(self.readValue() as! [Any?])
    case 135:
      return PasteButtonParams.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PasteLabelStyle {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PasteAlignmentDirection {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PasteAlignment {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PasteButtonBorderShape {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? VersionOverride {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PasteColor {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PasteButtonParams {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MessageFlutterApiProtocol {
  func flutterMethod(id idArg: Int64, data dataArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MessageFlutterApi: MessageFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonPigeonCodec {
    return PigeonPigeonCodec.shared
  }
  func flutterMethod(id idArg: Int64, data dataArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.swiftui_paste_button.MessageFlutterApi.flutterMethod\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg, dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
